services:
  db:
    image: postgres:16-alpine
    container_name: inventario-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventariodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: erickyamilrc/inventario-app:latest
    container_name: inventario-app-service
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: inventariodb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data: