spring.application.name=inventario

# Configuración de la base de datos H2
## Puerto de la aplicación: 8080
server.port=8080

## Configuración de BD (En memoria H2)
# spring.datasource.url=jdbc:h2:mem:inventariodb
# spring.datasource.username=sa
# spring.datasource.password=
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:inventariodb}
spring.datasource.url=${{ Inventario_bd.DATABASE_URL }}
# spring.datasource.username=${DB_USERNAME:postgres}
# spring.datasource.password=${DB_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

## JPA/Hibernate
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

## H2 Console (para verificar datos)
# spring.h2.console.enabled=true