spring.application.name=inventario

# Configuración de la base de datos H2
## Puerto de la aplicación: 8080
server.port=8080

## Configuración de BD (En memoria H2)
spring.datasource.url=jdbc:h2:mem:inventariodb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

## JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

## H2 Console (para verificar datos)
spring.h2.console.enabled=true